### ISSUE TITLE
Is this project for video only?

### ISSUE THREAD

**Issue by KCKCC** [DarkSouL11/flutter_torrent_streamer#1]
Hi, I happened to find this rare and interesting project.
But will this project for video only?
Do we have any chance to download any type of files?

**Comment by DarkSouL11** [comment]
This project is basically a flutter port for [this](https://github.com/TorrentStream/TorrentStream-Android) android library. But it shouldn't be very difficult to make a plugin that supports downloading any kind of file.

**Comment by KCKCC** [comment]
Cool! Thanks for the information!
